### ISSUE TITLE
Accept boolean inputs to call_service nodes

### ISSUE THREAD

**Issue by deece** [AYapejian/node-red-contrib-home-assistant#109]
I would like to turn a device on/off based on the state of a boolean.

I am currently using a function node with the following code to do this:
```
if (msg.bool) {
    msg.payload = {service: "turn_on"}
} else {
    msg.payload = {service: "turn_off"}
}
return msg;
```

The flow would be less cluttered if the call_service node could interpret booleans as calls to turn_on/turn_off.

**Comment by aidbish** [comment]
This repo is dead

Please use https://github.com/zachowj/node-red-contrib-home-assistant-websocket
