### ISSUE TITLE
history node not working

### ISSUE THREAD

**Issue by sophof** [AYapejian/node-red-contrib-home-assistant#11]
I know it says it is WIP, but it doesn't seem to be working at all at the moment. No string is saved and leaving it empty returns the following error: "Error calling service, home assistant api error".
You can tell no string is saved in the node, since if you write anything and save the node, you can't actually deploy the flow.

the plugin seems to be working great for all other nodes, so I just wanted to make clear people are actually using it and hoping for extra features :)

The mentioned ability to filter by entity_id would be great too (there doesn't seem to be any way to do that either atm)

**Comment by AYapejian** [comment]
Interesting, wonder if something changed with HA since I implemented this awhile back.  I'll have a look as soon as I can, might be a bit longer but I will get to it.

**Comment by sibbl** [comment]
Even if you try to pipe in a message like `{"payload":{"startdate": "2018-01-25T00:00:00.000Z"}}`, it will do a GET request to `HA/api/history/period/Thu Jan 25 2018 07:41:10 GMT+0000`. Not sure why such a broken code made it into this node - did it ever work for anyone?

**Comment by AYapejian** [comment]
@sibbl completely agree, this is both a bug and some cleanup/base features needed for the history node.

**Comment by AYapejian** [comment]
This has been merged into the dev branch, only fixes base use case of startdate ( either configured or overrides ).  Created #28 to address enhancements mentioned above

**Comment by AYapejian** [comment]
Done and merged, as mentioned, the much needed additional changes will be tackled as enhancements in the other issue.
