### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by mcfarlde** [AYapejian/node-red-contrib-home-assistant#12]
I can't get this add on to do anything in Hassio v0.60.  Where can I find some detailed examples?  All I can find is at  http://diyfuturism.com/index.php/2017/11/26/the-open-source-smart-home-getting-started-with-home-assistant-node-red/#more-22 and the simple timestamp to service example won't do anything for me.

**Comment by tehniemer** [comment]
Are you connected correctly? When you hit deploy do you see any errors in the debug tab?

**Comment by mcfarlde** [comment]
I am correctly connected now and have been successful with some flows for boolean on/off automation but am now working how to set a fan speed from a dashboard dropdown.  I tried using a function to make a payload with the selected speed to one service call with no success and am now trying to evaluate the string from the dropdown to make booleans that will fire one on 5 speed service calls.  I hse had what I think are good payloads going to the fan controller, but get no action and get errors in the log.  A result that I think should work . `msg.payload : Object
{ delay: 1000, set_speed: "low" } with the following in the log. `Invalid service data for fan.set_speed: required key not provided @ data['speed']. Got None

**Comment by tehniemer** [comment]
Huh, I'm actually trying to do the same thing with lights and getting a similar error.  My goal is to store the brighness in an ```input_number``` and pass it back. I haven't figured out how to pass a number into the data slot of a ```call service``` node from another node in the flow. This is the error I'm seeing:

```
2018-01-06 10:35:30 ERROR (MainThread) [homeassistant.core] Invalid service data for input_number.set_value: Entity ID input_number:test is an invalid entity id for dictionary value @ data['entity_id']. Got 'input_number:test'
required key not provided @ data['value']. Got None
```
