### ISSUE TITLE
current state does not output requested data

### ISSUE THREAD

**Issue by tehniemer** [AYapejian/node-red-contrib-home-assistant#13]
I'm trying to use ```current state``` to get the attribute ```brightness_pct``` for a light so I can store it in a variable for later use, but every time it only returns "on" or "off". This seems to be the case for all the available outputs. Below is the flow in question.

```
[{"id":"5a6af2b.170250c","type":"api-current-state","z":"cdd927d6.f1cc08","name":"","server":"4f0a8cab.0253b4","halt_if":"","entity_id":"light.den","x":320,"y":460,"wires":[["cd1181c7.6e04a"]],"outputLabels":["data.attributes.brightness_pct"]},{"id":"e06e7a3f.b10cc8","type":"inject","z":"cdd927d6.f1cc08","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":100,"y":460,"wires":[["5a6af2b.170250c"]]},{"id":"cd1181c7.6e04a","type":"debug","z":"cdd927d6.f1cc08","name":"","active":true,"console":"false","complete":"payload","x":550,"y":460,"wires":[]},{"id":"4f0a8cab.0253b4","type":"server","z":"","name":"Home Assistant","url":"localhost:8123:","pass":""}]
```

**Comment by mcfarlde** [comment]
Try a function to split the payload.  [{"id":"191a5968.3b5317","type":"function","z":"3cf03d1b.e63c92","name":"Table Lamp Split","func":"var retVal = [\n    null, null\n];\n\nif (msg.payload !== undefined)\n  msg = msg.payload;\n\nif (msg.on !== undefined)\n  retVal[0] = { payload: msg.on };\n\nif (msg.bri !== undefined)\n  retVal[1] = { payload: msg.bri };\n  \nif (msg.effect !== undefined)\n  retVal[2] = { payload: msg.effect };\n\nreturn retVal","outputs":"3","noerr":0,"x":410,"y":220,"wires":[["a51583d6.913c9"],["48485800.816808"],[]]}]

**Comment by tehniemer** [comment]
I'm not sure the data I'm looking for is actually getting passed. I have these lights hooked up to a Wink 2 hub, and this is the debug message I'm getting from polling the current attributes of the light.

```
1/6/2018, 10:40:34 AMnode: 738c32c4.e6806c
light.den : msg.payload : string[2]
"on"
```

**Comment by mcfarlde** [comment]
What I posted works with the Hue nodes where it is documented what is returned from a query.  The function splits the on/off state and brightness out to be adjusted and inserted back into a service call to control.  I've given up (for the moment) trying the same with the home assistant service nodes as they don't seem to accept incoming overwrites of whta is configured in them.  I have resorted to multiple service calls to the same device for different actions.

**Comment by tehniemer** [comment]
OK, wink must not report back anything other than "on" or "off", bummer. On another note, how do you insert data from a function into the data container of a home assistant service node? I've been failing miserably trying to use a function to control brightness.

**Comment by AYapejian** [comment]
@tehniemer you can pass in a message like below ( use a function node or some other transformation node to generate the data before the service node ).  If this isn't working and you verify it's not an HA issue then please open a bug with an example flow exported I can run to reproduce.

#### Function node contents prior to service node
```js
msg.payload = {
    domain:  'light',
    service: 'turn_on',
    data:    { entity_id: 'light.light1', transition: 10 }
};
return msg;
```
