### ISSUE TITLE
unable to pass topic as entity_id

### ISSUE THREAD

**Issue by Spartan-II-117** [AYapejian/node-red-contrib-home-assistant#14]
It would be awesome to pass the topic or payload as the entity_id in call_service, is there any way to do this currently?

**Comment by oakbrad** [comment]
You can override anything in the service call by passing a data { } object in the payload.

<code>msg.payload = { data: { 'entity_id': 'light.bulb', 'brightness':255 } }</code>

**Comment by Spartan-II-117** [comment]
where does that go? my goal is to use the topic (the triggered entity name) back to the call-service node. what would i need to put in the data to make that happen?
