### ISSUE TITLE
Current state prefers payload entity_id instead of configured one

### ISSUE THREAD

**Issue by sibbl** [AYapejian/node-red-contrib-home-assistant#17]
I started getting into Node RED automation with this plugin and my HA the last days. Unfortunately I struggled quite a lot since I used the "server events" node to get events. I then piped this into a "current state" node which was supposed to check another entity's state and halt if it was "off".

The problem is, that this "current state" node always uses the `entity_id` of the incoming payload instead of the one configured in the node itself. This means that it always checks the one of the output of the "server events" node's output. Is this intended and if so, why? When I specify an `entity_id` in the "current state" node, why is it not preferred? I think it would make sense to always use the configured `entity_id` unless it doesn't exist or is empty. However I'm afraid that it might break lots of existing flows...

If it's intended, I'd also suggest to document it somewhere. The documentation lacks basic details and one is forced to use the debug node and read through the JS code to find such things like described above.

**Comment by nordlead2005** [comment]
When you select a node look at the info tab on the right side of the screen. If you read "current state" node documentation it says

> Inputs
> payload.entity_id string
> Overrides or sets the entity_id for which the current state is being fetched

If you put a debug node on the "events: all" node, then you'll see that payload.entity_id is populated. So it does what it says it will do.

You can either use a change node and delete the property, or what most people do is they use one or more "events: changed" node. Note that the "events: changed" node uses a substring match, so an entity_id filter of binary_sensor will return state changes for all binary sensors in your HA setup.

**Comment by AYapejian** [comment]
@nordlead2005 is correct, by your description @sibbl everything seems to be functioning as designed.  My personal view on this was the node configuration value could be thought of like how environment values are used in many cli systems, if you don't pass a cli argument then the environment variable is used as a default, if you pass an argument ( the node input ) then the environment variable ( the default node value ) is discarded.

I do agree that the documentation needs some love however and to that end I created #22 for when I have time to address
