### ISSUE TITLE
Won't Parse Payload for Service

### ISSUE THREAD

**Issue by jmesberg** [AYapejian/node-red-contrib-home-assistant#19]
Docs suggest I should be able to send any/all of those to the node as an input and leave them blank in the node config. For example I want to specify the domain (light), and entity_id (kitchen_lights) in the config, but pass in the service "turn_on" or "turn_off" in the input message. Cannot figure out how to do this. I tried JSON {turn_on} but that isn't a full JSON statement and it doesn't like it. Tried just text, but it doesn't like that either. I get "Domain or Service not set, skipping call service". I don't know if this is an issue or I just don't understand how to format the payload input properly.

**Comment by x99percent** [comment]
{
    "domain" : "light",
    "service" : "turn_off",
    "data" : {
        "entity_id" : "light.hallway"
    }
}

**Comment by jmesberg** [comment]
Thank you!

John

**Comment by Spartan-II-117** [comment]
Please close the issue if it is no longer relevant.
