### ISSUE TITLE
unable to see nodess after reloding page <nodered_ip>:1880

### ISSUE THREAD

**Issue by papartmike** [AYapejian/node-red-contrib-home-assistant#2]
hi. I think this is a good job and a grate idea! My issue is that, after installation of the nodes, it occurs that the nodes desappear from node list. if I have a node in my flow, after reloading the page the node is unrecognized even if the "node-red-contrib-home-assistant" contrib is installed. to see them again I have to uninstall ad reinstall the contrib. any idea why?

I have installed it through manage palette. nodered preinstalled on the latest noobs.

thanks
mp

**Comment by AYapejian** [comment]
I'm guessing this happened after the update a while back.  Some of the code was refactored and node names changed.  If that's the case you can either re-create the effected nodes or manually edit the `flows.json` file and add the new names as defined in this projects `package.json` file. 

If that is not the case and you are still having difficulties then can you provide your flows.json file along with node-red logs.

**Comment by AYapejian** [comment]
Closing due to no updates from submitter
