### ISSUE TITLE
server-state-change node will listen to all events that start with configured entity_id

### ISSUE THREAD

**Issue by walthowd** [AYapejian/node-red-contrib-home-assistant#26]
Version 0.21, Node-Red 0.17.5, Home Assistant 0.61.

Steps to reproduce:

Add any two entities in Home Assistant where one entity starts with the name of another entity_id.

Example:

```
input_boolean:
  node-red-test:
    name: 'node-red-test'
  node-red-test-two:
    name: 'node rest test two"
```

Create a server-state-change node for entity_id 'node-red-test' that goes to a debug node.

Toggle the state of 'node-rest-test-two' and you will see a event that comes through, even though it should have stricter matching.

`[{"id":"a88fe394.568e9","type":"server-state-changed","z":"e0703c90.1a341","name":"node-red-test","server":"e2a02faf.48099","entityidfilter":"binary_sensor.node-red-test","haltifstate":"","x":180,"y":1173,"wires":[["65cb89b5.b8d458"]]},{"id":"65cb89b5.b8d458","type":"debug","z":"e0703c90.1a341","name":"","active":true,"console":"false","complete":"true","x":332,"y":1173,"wires":[]},{"id":"e2a02faf.48099","type":"server","z":"","name":"Home Assistant","url":"https://localhost:8123","pass":"XXXX"}]`

Expected behavior - server-state-change nodes should have strict matching based on the entity-id and only send through events that match the entity_id exactly.

**Comment by walthowd** [comment]
Looks like the issue is the .indexOf string matching on [node-server-state-changed.js, line 19.](https://github.com/AYapejian/node-red-contrib-home-assistant/blob/87219bc56fff5972f6c5477907e6c0e125c9928c/node-server-state-changed/node-server-state-changed.js#L19)

**Comment by flamingm0e** [comment]
Just noticed this bug last night too. Would match() work instead?

**Comment by walthowd** [comment]
@flamingm0e It's fixed in the Dev Merged branch now -- Here was my hackish fix in the meantime:

   ```
 shouldIncludeEvent: function shouldIncludeEvent(entityId, { entityIdFilter }) {
        if (!entityIdFilter) { return true; }
        //const found = entityIdFilter.filter(filterStr => (entityId.indexOf(filterStr) >= 0));
        //return found.length > 0;
        for (var i = 0; i < entityIdFilter.length; i++) {
                if(entityId == entityIdFilter[i]) {
                        return true;
                }
        }
        return false
```

[node-server-state-changed.txt](https://github.com/AYapejian/node-red-contrib-home-assistant/files/1718303/node-server-state-changed.txt)

**Comment by AYapejian** [comment]
Right, merged into master now.  State node has option to substring, exact or regex match what you enter.  The new state trigger node also has some handy conditions if that change doesn't satisfy your needs.

**Comment by walthowd** [comment]
Thank you!
