### ISSUE TITLE
History Node Enhancements

### ISSUE THREAD

**Issue by AYapejian** [AYapejian/node-red-contrib-home-assistant#28]
#11 fixed broken history node but the node only works with start-date.  Supporting enddate, filter entity, relative dates ( -90min from 'now' ) should be supported.

**Comment by shadowdrake** [comment]
Just adding a bump to this. I see it's still in your to-do list but this addition would be pretty fantastic for what I'm working on now. I'm fetching the history for the temperature sensors for my 3D printer and slicing the temperatures up and spitting them back out over MQTT to generate a graph on a touch screen connected to an ESP8266.

My HA instance is running on an RPI3 and calling up the full history for an hour takes some time (20-30 seconds), having a filtered request would make the call much faster.

**Comment by AYapejian** [comment]
Just merged a pull request in dev-master branch for this, should be in the next release.
