### ISSUE TITLE
Call service using payload properties

### ISSUE THREAD

**Issue by jptrsn** [AYapejian/node-red-contrib-home-assistant#3]
I'd like the ability to call a service (e.g. light.turn_on) and set the entity ID based on a msg property (e.g. msg.payload.entity_id).

**Comment by AYapejian** [comment]
This has been supported for awhile now and it's usage is documented on the `call service` node's info tab.  All you have to do is pass in the override, but it needs to be nested within the `data` property.  Example: `msg.payload = { data: { entity_id: 'light.office_1'} }`

**Comment by jptrsn** [comment]
Great! Thanks.

**Comment by oakbrad** [comment]
Apologies if this is a dumb question, but how do I pass multiple data points to a service call? ie setting the volume, I've tried a few variations of this...

`"{ data: { 'entity_id': 'media_player.stereo'},{'volume_level': '0.55' } }"`

**Comment by mcfarlde** [comment]
I can't get this add on to do anything in Hassio v0.60.  Where can I find some detailed examples?  All I can find is at  http://diyfuturism.com/index.php/2017/11/26/the-open-source-smart-home-getting-started-with-home-assistant-node-red/#more-22 and the simple timestamp to service example won't do anything for me.
