### ISSUE TITLE
cannot get /home assistant/services

### ISSUE THREAD

**Issue by stefanbergh** [AYapejian/node-red-contrib-home-assistant#31]
Hi

I can't get this to send any commands to HA. When I insert the 
"Call service"-node the error "Cannot get /home assistant/services" flashes for a few seconds. I run this on a Rpi3 with Raspbian and HA on another Rpi3 with Hassio.

On the Hassio I added the Node-red component and there everything works great but on the other one I can only get messages from HA but not send anything back.

Does anyone have an idea on how to solve this? I'm guessing it has something to do with permissions but I have nog idea where to start looking.

**Comment by walthowd** [comment]
Are you running SSL/Let's Encrypt on Home Assistant? Can you manually call the home assistant API with curl from your Raspbian Pi as [documented here](https://home-assistant.io/developers/rest_api/)?

**Comment by stefanbergh** [comment]
Well.. this is embarrassing. 

I hade forgotten to set an api-password. With that in place it works fine.

Thank you for pointing me in the right way to find that!
