### ISSUE TITLE
Unable to install with npm install

### ISSUE THREAD

**Issue by NameLessJedi** [AYapejian/node-red-contrib-home-assistant#39]
Hi,
Newbie here (at least as far as node/npm/node-red goes). 
I'm running HA and node-red on Linux box (Debian SID just updated). Fresh install of node-red (v 0.18.3). Attempting to install this package as HA user gives only this: 
```
.node-red$ npm install node-red-contrib-home-assistant
npm WARN package.json node-red-project@0.0.1 No repository field.
npm WARN package.json node-red-project@0.0.1 No README data
npm WARN package.json node-red-project@0.0.1 No license field.
npm ERR! git clone git@github.com:github:node-red/node-red undefined
npm ERR! git clone git@github.com:github:node-red/node-red undefined
npm ERR! notarget No compatible version found: node-red@'github:node-red/node-red#0.18.2'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.1.0","0.2.0","0.3.0","0.4.0","0.5.0","0.6.0","0.7.0","0.7.1","0.7.2","0.8.0","0.8.1","0.9.0","0.9.1","0.9.1-nocolors","0.10.0","0.10.1","0.10.2","0.10.3","0.10.4","0.10.6","0.10.8","0.10.8-2","0.10.8-3","0.10.9","0.10.10","0.11.0","0.11.1","0.11.2","0.12.0","0.12.1","0.12.2","0.12.3","0.12.4","0.12.5","0.13.0","0.13.1","0.13.2","0.13.3","0.13.4","0.14.0","0.14.1","0.14.2","0.14.3","0.14.4","0.14.5","0.14.6","0.15.0","0.15.1","0.15.2","0.15.3","0.16.0","0.16.1","0.16.2","0.17.0","0.17.2","0.17.3","0.17.4","0.17.5","0.18.0","0.18.1","0.18.2","0.18.3"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Linux 4.14.0-3-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "node-red-contrib-home-assistant"
npm ERR! cwd /home/ha/.node-red
npm ERR! node -v v8.9.3
npm ERR! npm -v 1.4.21
npm ERR! code ETARGET
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/hassio/.node-red/npm-debug.log
npm ERR! not ok code 0
```
Thanks for any help

**Comment by AYapejian** [comment]
This works for me with both npm and yarn, what version of npm are you using?

```
~/.ay/test is 📦 v1.0.0 via ⬢ v9.5.0 took 6s
➜ npm -v
5.6.0

~/.ay/test is 📦 v1.0.0 via ⬢ v9.5.0
➜ yarn -v
1.3.2
```

**Comment by NameLessJedi** [comment]
I'm using Debian unstable packaged version of npm (and all dependecies).
Version of npm is visible in the output above and I believe it's 1.4.12 (latest available as packaged by Debian):
apt show npm
Package: npm
Version: 1.4.21+ds-2
Priority: optional
Section: web
Maintainer: Debian Javascript Maintainers <pkg-javascript-devel@lists.alioth.debian.org>
Installed-Size: 1,915 kB
Depends: nodejs, node-abbrev (>= 1.0.4), node-ansi (>= 0.3.0-2), node-ansi-color-table, node-archy, node-block-stream, node-fstream (>= 0.1.22), node-fstream-ignore, node-github-url-from-git, node-glob (>= 3.1.21), node-graceful-fs (>= 2.0.0), node-inherits, node-ini (>= 1.1.0), node-lockfile, node-lru-cache (>= 2.3.0), node-minimatch (>= 0.2.11), node-mkdirp (>= 0.3.3), node-gyp (>= 0.10.9), node-nopt (>= 3.0.1), node-npmlog, node-once, node-osenv, node-read, node-read-package-json (>= 1.1.0), node-request (>= 2.25.0), node-retry, node-rimraf (>= 2.2.2), node-semver (>= 2.1.0), node-sha, node-slide, node-tar (>= 0.1.18), node-underscore, node-which
Homepage: http://github.com/isaacs/npm
Download-Size: 354 kB
APT-Manual-Installed: yes
APT-Sources: http://ftp.pl.debian.org/debian unstable/main amd64 Packages
Description: package manager for Node.js
 Node.js is an event-based server-side javascript engine.
 .
 npm is the package manager for the Node JavaScript platform.  It puts
 modules in place so that node can find them, and manages dependency
 conflicts intelligently.
 .
 It is extremely configurable to support a wide variety of use cases.
 Most commonly, it is used to publish, discover, install, and develop
 node programs.


Some weeks ago I had this  up'n'running on other computer (also Debian unstable). I was using previous version of your package (sorry don't recall exact number ; it had to be some 1-1.5 month ago). I've removed all on that one and wanted to start toying on more appropriate machine

**Comment by AYapejian** [comment]
So I suspect this is an issue with your version of `npm` not handling commit'ish tags in the `package.json` file.  You should either install the latest npm or yarn version and use those, depending on how your `PATH` is setup `npm -ig npm@latest`  may work for you to easily upgrade npm.  If upgrading npm is not an option than you can just clone this repo, remove the line for the node-red dependency in `package.json` then run `npm link` in the cloned directory and `npm link node-red-contrib-home-assistant` in the directory you'd normally `npm install` in.  Hopefully upgrading the package manager will be easy for you as the second is just a hack ;o)

**Comment by NameLessJedi** [comment]
Thx
I'll try the first route and report back :)

**Comment by NameLessJedi** [comment]
It worked :) It's bit messy cause now I have 2 npms. I'll figure out if I can safely remove the one provided by Debian later.
In case someone bumps here: proper command to install was `npm install -g npm@latest` and make sure you have git installed too.
Thx for help :)

**Comment by AYapejian** [comment]
👍
