### ISSUE TITLE
Use node inside of functions?

### ISSUE THREAD

**Issue by sysrun** [AYapejian/node-red-contrib-home-assistant#4]
Hi,

is it possible to use for ex. the current_state node inside of a function? I'd like to get the sun.sun state for example inside of a function which is called by a presence detection to activate (or not) a light

**Comment by AYapejian** [comment]
I'll add this to my list of items to implement, tagged as enhancement so I don't forget.

**Comment by AYapejian** [comment]
I've surfaced the states as well as available services and events on the global context in 0.3.0.  Each home assistant configuration will be camel-cased property under the 'homeassistant' global context obejct.  I recommend installing [node-red-contrib-contextbrowser](https://www.npmjs.com/package/node-red-contrib-contextbrowser) load the global context and explore what's available, its a helpful module to have handy ;)

**Comment by jmesberg** [comment]
Love the new update. I hope you know how much we appreciate your work!
