### ISSUE TITLE
Error using new Trigger: State node

### ISSUE THREAD

**Issue by jmesberg** [AYapejian/node-red-contrib-home-assistant#40]
I get error "Could not find userDir to use for database store" when I deploy this new node.

**Comment by AYapejian** [comment]
`userDir` should be set by node-red either via settings.js or command line switch.  Please review this link I came across, set the var and re-open should you have further issues.

https://nodered.org/blog/2015/02/25/changing-where-node-red-stores-data

**Comment by walthowd** [comment]
Same behaviour, for me, I did not have userDir set before, was just using $HOME/.node-red. I had to  edit settings.js to specify that same directory again as userDir for trigger node to work. 

IMHO, this should work by default.  As not setting userDir explicitly is the default node-red behaviour.

**Comment by jmesberg** [comment]
I’m still stuck here. Can you please let me know exactly how you edit
settings.js to get this to work? When I take the comments off

//    userDir:'$HOME/.node-red’

and then restart node-red it starts ok but is missing all of my flows
(blank flow editing screen).

Sorry for noob question….but really would like to get this new node
working.

John

On February 19, 2018 at 11:16:59 AM, walthowd (notifications@github.com)
wrote:

Same behaviour, for me, I did not have userDir set before, was just using
$HOME/.node-red. I had to edit settings.js to specify that same directory
again as userDir for trigger node to work.

IMHO, this should work by default. As not setting userDir explicitly is the
default node-red behaviour.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AYapejian/node-red-contrib-home-assistant/issues/40#issuecomment-366739566>,
or mute the thread

**Comment by AYapejian** [comment]
There is a lot of information here if you haven't checked it out: [node-red configuration docs](https://nodered.org/docs/configuration).  In your situation I'm assuming what's happening is your flows, by default ( line commented out ) are located somewhere different than `$HOME/.node-red` so when you uncomment it then node-red essentially creates a new directory and empty flows.  To fix you'll have to figure out where the flow file is stored by default, set the `settings.js` line to that directory and restart.
