### ISSUE TITLE
Error with Current State node starting with .30

### ISSUE THREAD

**Issue by jmesberg** [AYapejian/node-red-contrib-home-assistant#42]
My current state nodes don't work as of the upgrade to 0.30. Error thrown below:

[warn] [api-current-state:Check Humidity] local state cache missing, sending empty payload

**Comment by AYapejian** [comment]
See issue logged here, main workaround, manually set `userDir` in `settings.js`

https://github.com/AYapejian/node-red-contrib-home-assistant/issues/38
