### ISSUE TITLE
Exception in trigger:state node 

### ISSUE THREAD

**Issue by patrik3k** [AYapejian/node-red-contrib-home-assistant#45]
The trigger state node causes a exception when userDir is not specified in config.js

01/03/2018, 09:20:52 node: Door opened
msg : string[48] 
**"Could not find userDir to use for database store"**

This exception is thrown in base-nod.js in function async getDb()  at row 72

`let dbLocation = this.RED.settings.get('userDir');
`          

A better way to read this property is 
`let dbLocation = this.RED.settings.userDir;
`            

See https://github.com/node-red/node-red/issues/1543

**Comment by patrik3k** [comment]
Huge thanks for a great package. Its fantastic.

**Comment by AYapejian** [comment]
Thanks, and nice find.  I made the change and will be in the next release.
