### ISSUE TITLE
Can't install on new Node-Red docker

### ISSUE THREAD

**Issue by vexter0944** [AYapejian/node-red-contrib-home-assistant#48]
I just stood up a new node-red docker to test the newest version of this node - I can install the node, but after a restart of the docker container, I see this in the logs:
6 Mar 01:05:08 - [warn] ------------------------------------------------------
6 Mar 01:05:08 - [warn] [node-red/rpi-gpio] Info : Ignoring Raspberry Pi specific node
6 Mar 01:05:08 - [warn] [node-red-contrib-home-assistant/server] SyntaxError: Unexpected identifier
6 Mar 01:05:08 - [warn] [node-red-contrib-home-assistant/server-events] SyntaxError: Unexpected identifier
6 Mar 01:05:08 - [warn] [node-red-contrib-home-assistant/server-state-changed] SyntaxError: Unexpected identifier
6 Mar 01:05:08 - [warn] [node-red-contrib-home-assistant/trigger-state] SyntaxError: Unexpected identifier
6 Mar 01:05:08 - [warn] [node-red-contrib-home-assistant/poll-state] SyntaxError: Unexpected identifier
6 Mar 01:05:08 - [warn] [node-red-contrib-home-assistant/api-call-service] SyntaxError: Unexpected identifier (line:2)
6 Mar 01:05:08 - [warn] [node-red-contrib-home-assistant/api-current-state] SyntaxError: Unexpected identifier (line:1)
6 Mar 01:05:08 - [warn] [node-red-contrib-home-assistant/api-get-history] SyntaxError: Unexpected identifier (line:2)
6 Mar 01:05:08 - [warn] [node-red-contrib-home-assistant/api-render-template] SyntaxError: Unexpected identifier (line:2)

After everything loads - I can get into the node-red console and when I look for the HASS nodes to drag onto the screen, they are not there (they were there before the restart).  It still shows the node to be installed when I manage the palette.  

This is on node-red (using this image from docker hub nodered/node-red-docker:latest) - version 0.18.4.  I'm using the latest version of this node as far as I can tell.

Edit:  I tried 0.18.3, 0.18.2, 0.18.1, 0.18.0 as well.  Results were the same each time.  Docker is running on an Ubuntu VM on Proxmox.  Docker is  17.12.0-ce.

Edit(2):  I tried it on my QNAP (different Docker than my UBUNTU box) to make sure this wasn't something I had done wrong with Docker/rights etc on my UBUNTU box - same issue - running NR 0.17.5 container on the QNAP - he're log from QNAP:

6 Mar 16:47:33 - [info] Node-RED version: v0.17.5                                                                                                        
6 Mar 16:47:33 - [info] Node.js  version: v6.12.0                                                                                                        
6 Mar 16:47:33 - [info] Linux 4.2.8 x64 LE                                                                                                               
6 Mar 16:47:34 - [info] Loading palette nodes                                                                                                            
6 Mar 16:47:36 - [warn] ------------------------------------------------------                                                                           
6 Mar 16:47:36 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node                                                                            
6 Mar 16:47:36 - [warn] [server] SyntaxError: Unexpected identifier                                                                                      
6 Mar 16:47:36 - [warn] [server-events] SyntaxError: Unexpected identifier                                                                               
6 Mar 16:47:36 - [warn] [server-state-changed] SyntaxError: Unexpected identifier                                                                        
6 Mar 16:47:36 - [warn] [trigger-state] SyntaxError: Unexpected identifier                                                                               
6 Mar 16:47:36 - [warn] [poll-state] SyntaxError: Unexpected identifier                                                                                  
6 Mar 16:47:36 - [warn] [api-call-service] SyntaxError: Unexpected identifier (line:2)                                                                   
6 Mar 16:47:36 - [warn] [api-current-state] SyntaxError: Unexpected identifier (line:1)                                                                  
6 Mar 16:47:36 - [warn] [api-get-history] SyntaxError: Unexpected identifier (line:2)       

Also - mapping port 1881 to 1880 under Docker since node-red was already using 1880.  

If I can answer more questions, grab more logs etc, please let me know,

Thanks for the work on the node, enjoy it a lot!!

# #47

**Comment by vexter0944** [comment]
As another side note - installed node-red on an Ubuntu vm - brand new build - nothing else installed - when I installed the HASS node - this is what shows up in the error log - 

7 Mar 13:29:37 - [info] Creating new flow file
7 Mar 13:29:37 - [info] Server now running at http://127.0.0.1:1880/
7 Mar 13:29:37 - [info] Starting flows
7 Mar 13:29:37 - [info] Started flows
7 Mar 13:30:03 - [info] Installing module: node-red-contrib-home-assistant, version: 0.3.0
7 Mar 13:31:25 - [info] Installed module: node-red-contrib-home-assistant
7 Mar 13:31:25 - [info] Added node types:
7 Mar 13:31:25 - [info]  - node-red-contrib-home-assistant:api-call-service : SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
7 Mar 13:31:25 - [info]  - node-red-contrib-home-assistant:api-current-state : SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
7 Mar 13:31:25 - [info]  - node-red-contrib-home-assistant:api-get-history : SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
7 Mar 13:31:25 - [info]  - node-red-contrib-home-assistant:api-render-template : SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
7 Mar 13:31:25 - [info]  - node-red-contrib-home-assistant:poll-state : SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
7 Mar 13:31:25 - [info]  - node-red-contrib-home-assistant:server : SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
7 Mar 13:31:25 - [info]  - node-red-contrib-home-assistant:server-events : SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
7 Mar 13:31:25 - [info]  - node-red-contrib-home-assistant:server-state-changed : SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
7 Mar 13:31:25 - [info]  - node-red-contrib-home-assistant:trigger-state : SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

This does not appear to be Docker related so much as something to do with how this node was built and node-red.

**Comment by vexter0944** [comment]
Got some insight on this - The new 0.3.0 release of node-red-contrib-home-assistant is only compatible with Node.js in the LTS release series (currently 8.9.4). from a HASS user who ran into this to a point.

**Comment by x99percent** [comment]
I've noticed this as well, which has left me using:
```npm install node-red-contrib-home-assistant@0.2.1

Have you figured out a way to get 0.3.0 to install?

**Comment by vexter0944** [comment]
The only way I've been able to deal with this was to use a Docker container that someone else created who ran into the same thing.  marthoc/node-red is the name of the Docker image.  Otherwise, I'd assume it would involve the newer Node.js.  The place I picked up this bit of info was here: https://community.home-assistant.io/t/my-docker-stack/43548/113 - the user was marthocoo - hope this helps!

**Comment by x99percent** [comment]
Unfortunately, I'm using the nodered/node-red-docker:rpi Docker image. I wonder if I could upgrade Node.js in that image...

**Comment by vexter0944** [comment]
It's a thought.  I wish the author of this node would give us a little insight on this issue.  I'm hoping the author hasn't stopped development on this node, it's starting to feel a little abandoned unfortunately.

**Comment by walthowd** [comment]
@vexter0944 It's all pretty well documented here already:

https://github.com/AYapejian/node-red-contrib-home-assistant/issues/38

**Comment by vexter0944** [comment]
Thanks for the heads up on that @walthowd - did not catch that - much appreciated!

**Comment by kabturek** [comment]
https://hub.docker.com/r/nodered/node-red-docker/ docker image has new tags with upgraded node:
use `nodered/node-red-docker:v8`  (there is also rpi-v8 for those on rpi)

**Comment by oakbrad** [comment]
@kabturek That solved it for me, thank you. Just switch to a new Docker and was wondering what was going on...

**Comment by AYapejian** [comment]
Thanks for fielding this guys
