### ISSUE TITLE
Include payload value in service call data

### ISSUE THREAD

**Issue by damylen** [AYapejian/node-red-contrib-home-assistant#59]
I would like to send a notification using the notify/bot service that includes a value that I'm getting from a msg.payload. I tried all kinds of data fields. All combinations without quotes are not accepted by node-red, all others don't seem to work, like: 

{ "message" : "{{ payload.temperature }}" }
{ "message" : "{{ msg.payload.temperature }}" }
{ "message" : "{{ msg.payload }}" }

Sending a simple message, using { "message" : "test message" } works, so i'm confident that the service is working, just confused how to include the correct payload value. 

Any suggestions?

**Comment by dawiyo** [comment]
Since you're surrounding your variables in quotes, it's being sent as a string. Try it without the quotes and curly brackets like this:
```js
{ "message": msg.payload.temperature }
```

**Comment by damylen** [comment]
That was my first thought as well, but node-red starts complaining if you don't use quotes:

![image](https://user-images.githubusercontent.com/2181795/39055427-80a277b4-44b4-11e8-82ac-559ab6e2f74a.png)

**Comment by dawiyo** [comment]
Try putting this in a function node before the service call. Make sure your "Data" field (in the image above) just has `{}` in there.

```js
msg.payload: {
    data: {
        message: msg.payload.temperature
    }
}

return msg
```

**Comment by damylen** [comment]
Thank you, this works:

```
msg.payload =  {
    data: {
        message: msg.payload.temperature
    }
}
return msg;
```

I guess it would be more efficient if this extra step was not necessary, but for now it works ;-)

**Comment by declankenny** [comment]
@damylen Can this issue be closed?
