### ISSUE TITLE
Project management

### ISSUE THREAD

**Issue by Spartan-II-117** [AYapejian/node-red-contrib-home-assistant#60]
@AYapejian  do you want someone else to come alongside you to manage this project? it hasn't been touched an over 2 months, and it has a number of people trying to contribute. I'm not sure that i'm the best person for the job (not a programmer/don't know node, but i'd be willing to help out, or maybe someone else who has made a meaningful contributon to the project. 

It just seems that more could e accomplished here than is currently happening.

Alternately, if you are not interested in continuing to maintain it, should the project be forked?

**Comment by AYapejian** [comment]
Thanks for the offer.  Anyone is welcome to fork the repo of coarse, that being said I haven't abandoned the project I've just been busy with other life priorities the past month or two.   Going to start wading through issues and PRs and try and catch up a bit in the next few weeks.  Stay tuned. 

On the other ask, I'll have to look into breaking the project out of my personal repo if we're going to have multiple maintainers I think, I certainly am not against this it's just a matter of finding the time.  Let me see if I can get things back on track and then address this part afterwards if need be.

**Comment by Spartan-II-117** [comment]
when you do look into this, it might be worth seeing if it can be added to the official home-assistant repository

**Comment by rschaeuble** [comment]
Any news here, @AYapejian? The project looks quite dead at the moment, which is a pity. I think it would be beneficial to try and get new contributors on board.

Sure, everyone could just fork this project, but then a few months or a year down the line we'll probably have n+1 dead projects... And there would be more confusion for Node RED users having to decide which of those modules they should install.

Maybe you really could get this project under the HomeAssistant umbrella.
