### ISSUE TITLE
Current State – pass original state or multiple outputs

### ISSUE THREAD

**Issue by jamieshaw** [AYapejian/node-red-contrib-home-assistant#63]
Quick suggestion; the option to merge the previous message and current state (from node) into a single payload; or to pass the original message only if Current State does not match the "half if" value.

Essentially forming a quick gate if the state does not match (regex?).

I'm finding myself using `join` nodes, and loop functions to filter out a simple gate. 🙂

**Comment by jamieshaw** [comment]
It looks as though this functionality should've been added in release 0.3.1, but I can't seem to get it working. Toggling the override options for both payload and topic seem to have no effect?

**Comment by declankenny** [comment]
OK, my bad. The issue was in how we were handling the backward compatibilty for these node
`// default switches to true if undefined (backward compatibility
            const override_topic = this.nodeConfig.override_topic || true;
            const override_payload = this.nodeConfig.override_payload || true;`

Both of these are always going to return true. I will submit a new pull request...

**Comment by martinjuhasz** [comment]
A pullrequest to fix that bug was submitted 

https://github.com/AYapejian/node-red-contrib-home-assistant/pull/78
