### ISSUE TITLE
[documentation] get light brightness level

### ISSUE THREAD

**Issue by FezVrasta** [AYapejian/node-red-contrib-home-assistant#71]
Hi, sorry I'm not following the template because it's an issue about lack of documentation.

If I use the "current_state" node, it only returns `on` or `off`, how do I get other attributes like color or brightness?

Thanks.

**Comment by eithe** [comment]
Hi, put in a debug node and choose to debug the whole msg object. There you will see which extra data you receive from HA.

**Comment by FezVrasta** [comment]
Oh thanks! I did expect it to be in the payload. Thanks

![image](https://user-images.githubusercontent.com/5382443/39879676-c8e819a8-547b-11e8-88dc-7ef518d8a1f7.png)
