### ISSUE TITLE
Cant install v0.3.2 ANYWHERE!!!

### ISSUE THREAD

**Issue by JuniorGamingTime** [AYapejian/node-red-contrib-home-assistant#77]
Im really new to all this so im a bit lost but i have tried installing the Home Assistant node for a few days now. i've tried on Debian, windows and in Dockers and i get the same issue im trying to install version "0.3.2" (look at screenshots for issue)also running NodeRed v0.18.6

**Screenshots**
https://i.imgur.com/fjhBDkr.png

Thanks for the help in advance

**Comment by astogo** [comment]
This error should be gone if you change the underlying nodejs from v6 to v8.

**Comment by JuniorGamingTime** [comment]
Yeah I forgot to close this I found a little step by step of how to change the versions http://brodine.com/using-node-red-and-home-assistant-docker-containers-on-unraid/
